#pragma once

enum handler_id
{
	MAIN_FRAME_ID = 10000,
	SIDE_PANEL_ID,
	TOP_PANEL_ID,
	BOTTOM_PANEL_ID,
	WORK_PANEL_ID,
	MENU_FILE_EXIT_ID,
	MENU_FILE_NEW_PROJECT_ID,
	MENU_FILE_NEW_USER_ID,
	MENU_WINDOW_PROPERTIES_ID,
	MENU_HELP_ABOUT_ID,
	MAIN_1SEC_TIMER_ID,
	MAIN_SEARCH_ID,
	TOP_PANEL_SERACH_ID,
	TOP_PANEL_NEW_TASK_ID
};

wxDECLARE_EVENT(mwUpdateUI, wxCommandEvent);
wxDECLARE_EVENT(mwAppendTask, wxCommandEvent);
wxDECLARE_EVENT(mwNotification, wxCommandEvent);