#pragma once

#define MW_VERSION "1.1.2"

enum UI_COMPONENTS_ID
{
	MAIN_FRAME_ID = 10000,
	SIDE_PANEL_ID,
	TOP_PANEL_ID,
	BOTTOM_PANEL_ID,
	WORK_PANEL_ID,
	COLLAPSIBLE_NOTIFICATIONS_PANEL_ID,
	TASKS_WINDOW_ID,
	NOTIFICATIONS_WINDOW_ID,
	ARCHIVE_WINDOW_ID,
	MENU_FILE_EXIT_ID,
	MENU_FILE_NEW_PROJECT_ID,
	MENU_FILE_NEW_USER_ID,
	MENU_WINDOW_PROPERTIES_ID,
	MENU_WINDOW_REFRESH_ID,
	MENU_HELP_ABOUT_ID,
	MAIN_1SEC_TIMER_ID,
	MAIN_SEARCH_ID,
	TOP_PANEL_SERACH_ID,
	TOP_PANEL_NEW_TASK_ID,
	TOP_PANEL_NEW_PROJECT_ID
};

wxDECLARE_EVENT(mwUpdateUI, wxCommandEvent);
wxDECLARE_EVENT(mwAppendTask, wxCommandEvent);
wxDECLARE_EVENT(mwNotification, wxCommandEvent);